### ISSUE TITLE
Sometimes, new stocks don't get added properly

### ISSUE THREAD

**Issue by alcfeoh** [AdrienBEH/adrienbeh.github.io#1]
Cette erreur arrive assez fréquemment, environ une fois sur 2 ou 3 :

![image](https://user-images.githubusercontent.com/4699771/196291414-d6d5d73b-51f0-4967-a850-dc3bfba16280.png)

**Comment by AdrienBEH** [comment]
Merci @alcfeoh. Important : changement d'URL de l'application pour [https://angularcertif2.web.app](https://angularcertif2.web.app) depuis #2 ; l'ancienne URL `https://adrienbeh.github.io` est obsolète.

Nouveau déploiement effectué avec résolution du comportement.

Procédure de reproduction :
```
0. arriver sur la page `/symbols`, aucun symbol stocké
1. rechercher et stocker un symbol
2. en cliquant sur le bouton `DETAILS` de ce symbole, accéder à la page `/sentiment/:symbol`
4. en cliquant sur le bouton `STOCK`, revenir sur la page `/symbols`
5. rechercher et stocker un symbol
6. rechercher et stocker un symbol
7. cliquer sur le bouton `DETAILS` de ce dernier symbol
8. la snackbar d'information de symbol non stocké apparaît, l'accès à la page `/sentiment/:symbol` de ce dernier symbol n'est pas possible
```
